name: single_chat
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_core: ^0.7.0
  shared_preferences: ^0.5.12+4

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: BungeeInline
      fonts:
        - asset: assets/fonts/BungeeInline-Regular.ttf
          weight: 700
#    - family: Ubuntu
#      fonts:
#        - asset: assets/fonts/Ubuntu-Regular.ttf